Mass update of Apps
NubeIO/rubix-service pull request #145
Opened 2021-04-22 09:11 UTC by enjuthulung

Resolves: #144
### Summary:
- Added POST endpoint api/app/update_apps. Examples:
   ```
     curl -x POST http://localhost:1616/api/app/update_apps -H “Content-Type: application/json” -d
        ‘{
             "apps":[
                  {
                          "service": "POINT_SERVER",
                          "version": "v1.6.1",
                          "delete_config": false
                  },
                  {
                          "service": "RUBIX_PLAT",
                          "version": "v1.4.5",
                          "delete_db": true
                  }
             ]
         }’
    ```

2021-04-22 22:10 UTC, NubeDev commented
The thing if we do it in one big HTTP POST it could take 10min to update all the apps when the internet is bad

So could we either publish some messages over MQTT so the UI can see the updates happen or send some WS of each stage of the updates

2021-05-11 05:33 UTC, sanjevShakya commented
![bulk_app_download_system_seq](https://user-images.githubusercontent.com/9900412/117763470-10473b00-b255-11eb-844c-3d641b000e93.jpg)

Tentative system sequence diagram to handle bulk app download

2021-05-13 10:00 UTC, RaiBnod requested changes
Add that delete service api part as well.

2021-05-15 04:40 UTC, RaiBnod approved these changes

2021-05-15 04:41 UTC, merged