Jwt integration
NubeIO/rubix-service pull request #56
Opened 2021-01-15 03:58 UTC by enjuthulung

2021-01-15 03:58 UTC, zero88 requested changes

2021-01-15 03:58 UTC, zero88 commented on src/app.py
> +    app.config['SECRET_KEY'] = 'lB0YZkBexl9sH7zklYeaobVwoGJbQRalWkTHKNJhy/A='
Must be in config file

2021-01-15 12:09 UTC, RaiBnod requested changes
Following improvements needed to do:

- Move your `SECRET_KEY` stored on some other file, like in `TOKEN`
- Make single entry for `@authorize` and make it configurable

2021-01-18 12:47 UTC, RaiBnod approved these changes

2021-01-18 12:48 UTC, merged